Testing release action 169

diff --git a/.github/actions/extract-version/action.yml b/.github/actions/extract-version/action.yml
--- a/.github/actions/extract-version/action.yml
+++ b/.github/actions/extract-version/action.yml
@@ -13,6 +13,14 @@ runs:
       shell: bash
       run: ./.github/scripts/extract-versions.sh "${{ inputs.tag-name }}"
 
+    - name: Validate version
+      shell: bash
+      run: |
+        if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid version format: $VERSION"
+          exit 1
+        fi
+
     - name: Log version
       shell: bash
       run: |
